### PR TITLE
Correct copyright statement

### PR DESCRIPTION
**Pull request by fulldecent**
I understand Compound Labs, Inc does not have a registered trade name of "Compound Labs" (without the Inc). This PR fixes the copyright statement.

### CODE REVIEW

**Comment by fulldecent** [comment]
To be clear, are you still accepting contributions to this project?? If so is this PR in scope to be merged?

**Comment by fulldecent** [comment]
Ping.

**Comment by hayesgm** [comment]
As this code exists in immutable form on the blockchain, we have decided to move conversation to Discord, as the GitHub pull request and issue model does not provide the same benefits as it would for code that is upgraded over time. Join us in our [#Development Discord](https://discordapp.com/channels/402910780124561410/402912055448961034) for any questions regarding this or other Compound contracts or development questions.

**Comment by fulldecent** [comment]
You may consider to adopt the model from Su Squares -- https://github.com/su-squares/ethereum-contract

This shows the roles that issues and pull requests have in improving deployed blockchain projects. (Hint: it is mostly around tests.)

Discord will not provide much value for this since tests should be collected over time, not discussed ephemerally.

**Pull request closed without merging**
